Q1.Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np
list=['1','2','3','4','5']
array_list= np.array(object=list)
type(list)

list

In [3]:
type(array_list)

numpy.ndarray

Q6.Create an identity matrix of shape (5,5) using numpy functions?

In [6]:
import numpy as np
arr1=np.identity(5)
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Q5.Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [9]:
arr2=np.zeros((3,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr2.shape

(3, 3)

In [11]:
arr2.size

9

Q2.Write a code to print the data type of each and every element of both the variables list_ and arra_list.
ANS:



In [15]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print("Data type in list:")
for item1 in list_:
    print(type(item1))

print("data type of array list:")
for item in array_list:
    print(type(item))

Data type in list:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
data type of array list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


 Q4.Write a code to find the following characteristics of variable, num_array:
(i)	 shape
(ii) size

In [21]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print("Shape of NumList:")
shape=np.shape(num_list)
print(shape)
print("Size of NumList:")
size=np.size(num_list)
print(size)
print("Shape of NumArray:")
shape1=np.shape(num_array)
print(shape1)
print("Size of  NumArray:")
size1=np.size(num_array)
print(size1)

Shape of NumList:
(2, 3)
Size of NumList:
6
Shape of NumArray:
(2, 3)
Size of  NumArray:
6
