In [11]:
from sklearn.datasets import load_iris

In [12]:
dataset=load_iris()

In [13]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [14]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [15]:
import pandas as pd
import numpy as np

In [16]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [17]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [18]:
df['target']=dataset.target

In [19]:
df.drop('target',axis=1,inplace=True)

In [22]:
df['target']=dataset.target

In [23]:
df.target

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [24]:
df_copy=df[df['target']!=2]

In [25]:
df_copy.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
95       1  
96       1  
97       1  
98       1  
99       1

In [26]:
##independent And Dependent Feature 

In [27]:
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [28]:
X,y

(    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                 5.1               3.5                1.4               0.2
 1                 4.9               3.0                1.4               0.2
 2                 4.7               3.2                1.3               0.2
 3                 4.6               3.1                1.5               0.2
 4                 5.0               3.6                1.4               0.2
 ..                ...               ...                ...               ...
 95                5.7               3.0                4.2               1.2
 96                5.7               2.9                4.2               1.3
 97                6.2               2.9                4.3               1.3
 98                5.1               2.5                3.0               1.1
 99                5.7               2.8                4.1               1.3
 
 [100 rows x 4 columns],
 0     0
 1     0
 2     0
 3     0
 

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

splitting the data (train test )

In [30]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=30)

In [31]:
classifire=LogisticRegression()

In [32]:
classifire.fit(X_train,y_train)

LogisticRegression()

In [33]:
classifire.predict_proba(X_test)

array([[0.95565528, 0.04434472],
       [0.00630133, 0.99369867],
       [0.96910638, 0.03089362],
       [0.00236057, 0.99763943],
       [0.9756279 , 0.0243721 ],
       [0.0108065 , 0.9891935 ],
       [0.97616841, 0.02383159],
       [0.02493469, 0.97506531],
       [0.03514549, 0.96485451],
       [0.02085607, 0.97914393],
       [0.02989631, 0.97010369],
       [0.98198776, 0.01801224],
       [0.98092824, 0.01907176],
       [0.00156276, 0.99843724],
       [0.98486969, 0.01513031],
       [0.02330625, 0.97669375],
       [0.0033949 , 0.9966051 ],
       [0.0221276 , 0.9778724 ],
       [0.97847934, 0.02152066],
       [0.97761698, 0.02238302]])

In [34]:
y_pred=classifire.predict(X_test)

In [35]:
y_pred

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0])

Confusion Matrix, Accuracy score,Classification report

In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [37]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[ 9  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



HyperParameter Tuning
1.GridSerchCV
2.RandomizedSerchCV

In [38]:
#GridSerchCV

In [39]:
#Gridserchcv
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [40]:
parameter={'penalty':('l1', 'l2', 'elasticnet', None),'solver':('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'),'C':[1,10,20]},

In [41]:
clf=GridSearchCV(classifire,param_grid=parameter,cv=5)

Splitting tarin data into validation data 

In [42]:
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid=({'C': [1, 10, 20],
                          'penalty': ('l1', 'l2', 'elasticnet', None),
                          'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                     'newton-cholesky', 'sag', 'saga')},))

In [43]:
clf.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [44]:
classifire=LogisticRegression(C= 1, penalty='l1', solver ='liblinear')

In [45]:
classifire.fit(X_train,y_train)

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [46]:
y_pred=classifire.predict(X_test)

In [47]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[ 9  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



Randamoizesed Search Cv

In [51]:
from sklearn.model_selection import RandomizedSearchCV

In [54]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameter,cv=5)

In [55]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions=({'C': [1, 10, 20],
                                         'penalty': ('l1', 'l2', 'elasticnet',
                                                     None),
                                         'solver': ('lbfgs', 'liblinear',
                                                    'newton-cg',
                                                    'newton-cholesky', 'sag',
                                                    'saga')},))

In [56]:
random_clf.best_params_


{'solver': 'newton-cholesky', 'penalty': 'l2', 'C': 20}

In [58]:
classifire=LogisticRegression(solver = 'newton-cholesky', penalty='l2', C= 20)

In [59]:
classifire.fit(X_train,y_train)

LogisticRegression(C=20, solver='newton-cholesky')

In [60]:
y_pred=classifire.predict(X_test)

In [61]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[ 9  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

