ONE HOT ENCODING

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [6]:
df=pd.DataFrame({'color':['red','blue','white','red','white','blue']})

In [7]:
df

color
0    red
1   blue
2  white
3    red
4  white
5   blue

In [8]:
#Crete an instace of one hot encoder
encoder=OneHotEncoder()

In [12]:
encoder.fit_transform(df[['color']])

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [10]:
##encoder.fit_transform(df[['color']]).toarray()

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [14]:
#fit the encoder to dataframe and transform the categorical variabel 
encoded=encoder.fit_transform(df[['color']])

In [17]:
import pandas as pd 
encoded_df=pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [18]:
pd.concat([df,encoded_df],axis=1)

color  color_blue  color_red  color_white
0    red         0.0        1.0          0.0
1   blue         1.0        0.0          0.0
2  white         0.0        0.0          1.0
3    red         0.0        1.0          0.0
4  white         0.0        0.0          1.0
5   blue         1.0        0.0          0.0

In [19]:
import seaborn as sns

In [28]:
df1=sns.load_dataset('tips')

In [29]:
df1

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [23]:
encoder1=OneHotEncoder()

In [25]:
encoded1=encoder1.fit_transform(df[['sex','smoker','day']])

In [26]:
import pandas as pd 
encoded_df1=pd.DataFrame(encoded1.toarray(),columns=encoder1.get_feature_names_out())

In [27]:
encoded_df1

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
..          ...       ...        ...         ...      ...      ...      ...   
239         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
240         1.0       0.0        0.0         1.0      0.0      1.0      0.0   
241         0.0       1.0        0.0         1.0      0.0      1.0      0.0   
242         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
243         1.0       0.0        1.0         0.0      0.0      0.0      0.0   

     day_Thur  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  
..        ...  
239       0.0  
240       0.0  
241       0.0  
242       0.0  
243       1.0  

[244 rows x 8 columns]

In [34]:
pd.concat([df1,encoded_df1],axis=1)

total_bill   tip     sex smoker   day    time  size  sex_Female  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0   
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0   

     sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  
0         0.0        1.0         0.0      0.0      0.0      1.0       0.0  
1         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
2         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
3         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
4         0.0        1.0         0.0      0.0      0.0      1.0       0.0  
..        ...        ...         ...      ...      ...      ...       ...  
239       1.0        1.0         0.0      0.0      1.0      0.0       0.0  
240       0.0        0.0         1.0      0.0      1.0      0.0       0.0  
241       1.0        0.0         1.0      0.0      1.0      0.0       0.0  
242       1.0        1.0         0.0      0.0      1.0      0.0       0.0  
243       0.0        1.0         0.0      0.0      0.0      0.0       1.0  

[244 rows x 15 columns]

In [59]:
df1.columns.to_list()

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

LABLE AND ORDINAL ENCODING

In [62]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [63]:
df=pd.DataFrame({'color':['red','blue','white','red','white','blue']})

In [64]:
df

color
0    red
1   blue
2  white
3    red
4  white
5   blue

In [65]:
#Create an instance of LabelEncoder

encoder=LabelEncoder()

In [66]:
encoder.fit_transform(df['color'])

array([1, 0, 2, 1, 2, 0])

In [67]:
#Ordinal Ecnding 

In [75]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd 

df=pd.DataFrame({'size':['small','medium','large','small','medium','large']})

In [76]:
#Create an instance for ordinal Encoder calss and fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [77]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.]])

3. TARGET GUIDED ORDINAL ENCODING 

In [78]:
import pandas as pd

In [92]:
df=pd.DataFrame({
    'city':['bang','pune','mumbai','bang','mumbai','jalgaon'],
    'price':['300','250','300','150','320','180']
})

In [93]:
df.head()


city price
0    bang   300
1    pune   250
2  mumbai   300
3    bang   150
4  mumbai   320

In [94]:
##calacule mean price for each city
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price

{'bang': 150075.0, 'jalgaon': 180.0, 'mumbai': 150160.0, 'pune': 250.0}

In [90]:
##Replce each city with mean price
df['city_encoded']=df['city'].map(mean_price)

In [91]:
df

city price  city_encoded
0     bang   300      150075.0
1     pune   250         250.0
2   mumbai   300      150160.0
3     bang   150      150075.0
4   mumbai   320      150160.0
5  jalgaon   180         180.0

In [95]:
import seaborn as sns

In [97]:
df1=sns.load_dataset('tips')

In [104]:
df1.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [106]:
mean_price1=df1.groupby('day')['total_bill'].mean().to_dict()

In [107]:
mean_price1

{'Thur': 17.682741935483868,
 'Fri': 17.15157894736842,
 'Sat': 20.44137931034483,
 'Sun': 21.41}

In [108]:
df1['day_encoded']=df1['day'].map(mean_price1)

In [110]:
df1.tail()

total_bill   tip     sex smoker   day    time  size day_encoded
239       29.03  5.92    Male     No   Sat  Dinner     3   20.441379
240       27.18  2.00  Female    Yes   Sat  Dinner     2   20.441379
241       22.67  2.00    Male    Yes   Sat  Dinner     2   20.441379
242       17.82  1.75    Male     No   Sat  Dinner     2   20.441379
243       18.78  3.00  Female     No  Thur  Dinner     2   17.682742