In [ ]:
#Numpt - Array Manipulition

In [1]:
import numpy as np

In [3]:
arr= np.random.randint(1,10 ,(3,4))

In [4]:
arr

array([[7, 4, 8, 6],
       [6, 1, 3, 6],
       [4, 5, 9, 6]])

In [5]:
arr.reshape(6,2)

array([[7, 4],
       [8, 6],
       [6, 1],
       [3, 6],
       [4, 5],
       [9, 6]])

In [6]:
arr.reshape(2,6)

array([[7, 4, 8, 6, 6, 1],
       [3, 6, 4, 5, 9, 6]])

In [7]:
arr

array([[7, 4, 8, 6],
       [6, 1, 3, 6],
       [4, 5, 9, 6]])

In [8]:
arr.T

array([[7, 6, 4],
       [4, 1, 5],
       [8, 3, 9],
       [6, 6, 6]])

In [9]:
arr.flatten()

array([7, 4, 8, 6, 6, 1, 3, 6, 4, 5, 9, 6])

In [10]:
arr1=np.array([1,2,3,4,5])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [14]:
arr

array([[7, 4, 8, 6],
       [6, 1, 3, 6],
       [4, 5, 9, 6]])

In [15]:
np.squeeze(arr)

array([[7, 4, 8, 6],
       [6, 1, 3, 6],
       [4, 5, 9, 6]])

In [16]:
data = np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 4, 5])

In [21]:
np.repeat(arr1 ,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [25]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [24]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
#Numpy - Binary Operation

In [29]:
arr1 = np.random.randint(1,10,(3,4))

In [30]:
arr1

array([[5, 5, 2, 6],
       [3, 4, 9, 5],
       [2, 3, 7, 5]])

In [31]:
arr2 = np.random.randint(1,10,(3,4))

In [32]:
arr2

array([[9, 9, 7, 2],
       [8, 2, 2, 2],
       [3, 8, 9, 1]])

In [33]:
arr1+arr2

array([[14, 14,  9,  8],
       [11,  6, 11,  7],
       [ 5, 11, 16,  6]])

In [34]:
arr1*arr2

array([[45, 45, 14, 12],
       [24,  8, 18, 10],
       [ 6, 24, 63,  5]])

In [35]:
arr1/arr2

array([[0.55555556, 0.55555556, 0.28571429, 3.        ],
       [0.375     , 2.        , 4.5       , 2.5       ],
       [0.66666667, 0.375     , 0.77777778, 5.        ]])

In [36]:
arr1-arr2

array([[-4, -4, -5,  4],
       [-5,  2,  7,  3],
       [-1, -5, -2,  4]])

In [38]:
arr1%arr2

array([[5, 5, 2, 0],
       [3, 0, 1, 1],
       [2, 3, 7, 0]])

In [39]:
arr1 ** arr2

array([[ 1953125,  1953125,      128,       36],
       [    6561,       16,       81,       25],
       [       8,     6561, 40353607,        5]])

In [40]:
arr1 & arr2

array([[1, 1, 2, 2],
       [0, 0, 0, 0],
       [2, 0, 1, 1]])

In [41]:
arr1 | arr2

array([[13, 13,  7,  6],
       [11,  6, 11,  7],
       [ 3, 11, 15,  5]])

In [42]:
arr1>arr2

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [False, False, False,  True]])

In [44]:
arr=np.array(['tush','ahire'])

In [45]:
arr

array(['tush', 'ahire'], dtype='<U5')

In [46]:
np.char.upper(arr)

array(['TUSH', 'AHIRE'], dtype='<U5')

In [47]:
np.char.title(arr)

array(['Tush', 'Ahire'], dtype='<U5')

In [48]:
np.char.capitalize(arr)

array(['Tush', 'Ahire'], dtype='<U5')

In [49]:
np.char.lower(arr)

array(['tush', 'ahire'], dtype='<U5')

In [50]:
np.sin(arr1)

array([[-0.95892427, -0.95892427,  0.90929743, -0.2794155 ],
       [ 0.14112001, -0.7568025 ,  0.41211849, -0.95892427],
       [ 0.90929743,  0.14112001,  0.6569866 , -0.95892427]])

In [51]:
np.cos(arr1)

array([[ 0.28366219,  0.28366219, -0.41614684,  0.96017029],
       [-0.9899925 , -0.65364362, -0.91113026,  0.28366219],
       [-0.41614684, -0.9899925 ,  0.75390225,  0.28366219]])

In [52]:
np.tan(arr1)

array([[-3.38051501, -3.38051501, -2.18503986, -0.29100619],
       [-0.14254654,  1.15782128, -0.45231566, -3.38051501],
       [-2.18503986, -0.14254654,  0.87144798, -3.38051501]])

In [53]:
np.log10(arr1)

array([[0.69897   , 0.69897   , 0.30103   , 0.77815125],
       [0.47712125, 0.60205999, 0.95424251, 0.69897   ],
       [0.30103   , 0.47712125, 0.84509804, 0.69897   ]])

In [54]:
np.exp(arr1)

array([[1.48413159e+02, 1.48413159e+02, 7.38905610e+00, 4.03428793e+02],
       [2.00855369e+01, 5.45981500e+01, 8.10308393e+03, 1.48413159e+02],
       [7.38905610e+00, 2.00855369e+01, 1.09663316e+03, 1.48413159e+02]])

In [55]:
np.sqrt(arr1)

array([[2.23606798, 2.23606798, 1.41421356, 2.44948974],
       [1.73205081, 2.        , 3.        , 2.23606798],
       [1.41421356, 1.73205081, 2.64575131, 2.23606798]])

In [56]:
np.power(arr1,2)

array([[25, 25,  4, 36],
       [ 9, 16, 81, 25],
       [ 4,  9, 49, 25]], dtype=int32)

In [57]:
np.mean(arr1)

4.666666666666667

In [60]:
np.median(arr1)

5.0

In [61]:
np.std(arr1)

1.9720265943665387

In [62]:
np.max(arr1)

9

In [63]:
np.min(1)

1