In [1]:
#sort ,Serch & counting function

In [2]:
import numpy as np

In [4]:
arr=np.array([4,5,6,7,8,4,3,2,2,45,])

In [6]:
np.sort(arr)

array([ 2,  2,  3,  4,  4,  5,  6,  7,  8, 45])

In [7]:
np.searchsorted(arr,24)

9

In [8]:
arr1= np.array([0,243,434,242,23,24,0,0,0,23,30])

In [9]:
np.count_nonzero(arr1)

7

In [10]:
arr

array([ 4,  5,  6,  7,  8,  4,  3,  2,  2, 45])

In [11]:
np.where(arr >6)

(array([3, 4, 9], dtype=int64),)

In [12]:
np.extract(arr >6,arr)

array([ 7,  8, 45])

In [13]:
#Numpy -Byte Swapping.


In [14]:
arr.byteswap()

array([ 67108864,  83886080, 100663296, 117440512, 134217728,  67108864,
        50331648,  33554432,  33554432, 754974720])

In [15]:
#Numpy -Copies & Views


In [16]:
arr

array([ 4,  5,  6,  7,  8,  4,  3,  2,  2, 45])

In [17]:
import numpy.matlib as nm

In [18]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [19]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
#Numpy - Liner Algebra

In [22]:
arr1=np.random.randint([[2,3],[4,5]])
arr2=np.random.randint([[5,3],[4,2]])

In [23]:
np.dot(arr1,arr2)

array([[2, 0],
       [4, 2]])

In [24]:
arr1@arr2

array([[2, 0],
       [4, 2]])