In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4, 5])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
a=[1,2,3]

In [11]:
np.asanyarray(a)

array([1, 2, 3])

In [12]:
b=np.matrix(l)#matrix is 2D

In [13]:
b

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [15]:
a=np.array(l)

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
c=a#shall copy 

In [18]:
c

array([1, 2, 3, 4, 5])

In [19]:
c[0]=100

In [20]:
c

array([100,   2,   3,   4,   5])

In [21]:
a

array([100,   2,   3,   4,   5])

In [22]:
d= np.copy(a)#deep copy 

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
d

array([100,   2,   3,   4,   5])

In [25]:
a[1]=400

In [26]:
a

array([100, 400,   3,   4,   5])

In [27]:
d

array([100,   2,   3,   4,   5])

In [28]:
np.fromfunction(lambda i ,j :i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i ,j :i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
iterable=( i*i for i in range(6))

In [31]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [32]:
np.fromstring('244 533',sep=' ')

array([244., 533.])

In [33]:
np.fromstring('5,3', sep=',')

array([5., 3.])

In [34]:
#Numpy - Data Types

In [35]:
l

[1, 2, 3, 4, 5]

In [36]:
ar

array([1, 2, 3, 4, 5])

In [37]:
ar.ndim

1

In [39]:
ar2=np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [40]:
ar2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [41]:
ar2.ndim

2

In [42]:
ar.size

5

In [44]:
ar2.size

10

In [45]:
ar.shape

(5,)

In [46]:
ar2.shape

(2, 5)

In [47]:
ar.dtype

dtype('int32')

In [48]:
ar2.dtype

dtype('int32')

In [49]:
ar22=np.array([[1.4,46,38],[83,53,23]])

In [50]:
ar22

array([[ 1.4, 46. , 38. ],
       [83. , 53. , 23. ]])

In [51]:
ar22.dtype

dtype('float64')

In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
np.arange(2.3,5.8)

array([2.3, 3.3, 4.3, 5.3])

In [55]:
np.arange(2.3,5.8,0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6])

In [57]:
list(np.arange(2.3,5.8,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998,
 5.599999999999998]

In [58]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [62]:
np.ones(4)

array([1., 1., 1., 1.])

In [64]:
on=np.ones((2,3,4))

In [65]:
on +5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [66]:
on*4

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [69]:
np.empty((3,9))

array([[6.27365591e-312, 6.27339015e-312, 1.69121096e-306,
        1.69121503e-306, 8.34451079e-308, 1.60219578e-306,
        6.23037317e-307, 2.22526399e-307, 6.23053614e-307],
       [1.29060871e-306, 6.23055651e-307, 1.06811422e-306,
        3.56043054e-307, 1.37961641e-306, 9.45697982e-308,
        1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
       [2.78149851e-307, 1.06811422e-306, 8.45590539e-307,
        6.23054972e-307, 9.34609790e-307, 1.78019354e-306,
        1.69119330e-306, 1.24611470e-306, 2.56765117e-312]])

In [70]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [72]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [74]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [76]:
arr= np.random.randn(3,4)

In [77]:
import pandas as pd 

In [78]:
pd.DataFrame(arr)

0         1         2         3
0  1.760240 -1.710176 -1.464146 -0.642411
1  0.181353 -0.386061 -0.943339  2.066595
2 -1.010206 -0.142780 -1.036402 -0.133001

In [79]:
np.random.randint(1,100,(300,400))

array([[ 4, 46, 76, ..., 55, 53, 91],
       [49, 70,  3, ..., 93, 20, 59],
       [41, 13, 58, ..., 53, 94, 99],
       ...,
       [42, 35, 74, ..., 10, 56, 55],
       [ 8, 17, 98, ..., 62, 21, 29],
       [31, 82,  4, ..., 23, 94, 83]])

In [81]:
pd.DataFrame(np.random.randint(1,100,(300,400))).to_csv('test.csv')

In [82]:
arr1=np.random.rand(3,4)

In [83]:
arr1

array([[0.84803621, 0.06596813, 0.98671121, 0.46907102],
       [0.19733203, 0.48252488, 0.46885362, 0.24899787],
       [0.80978238, 0.08121996, 0.56999398, 0.54388774]])

In [87]:
arr1=arr1.reshape(6,2)

In [88]:
arr1

array([[0.84803621, 0.06596813],
       [0.98671121, 0.46907102],
       [0.19733203, 0.48252488],
       [0.46885362, 0.24899787],
       [0.80978238, 0.08121996],
       [0.56999398, 0.54388774]])

In [89]:
arr1[1][1]

0.4690710218524289

In [92]:
arr1[3][1]

0.24899786786212508

In [94]:
arr1[2:5,1]

array([0.48252488, 0.24899787, 0.08121996])

In [96]:
arr=np.random.randint(1,100,(5,5))

In [97]:
arr

array([[72, 39, 21, 12, 84],
       [66, 79, 54, 70, 83],
       [90, 92, 25, 46, 33],
       [77, 38, 36, 61, 68],
       [12, 94, 73, 30, 80]])

In [98]:
arr>50

array([[ True, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [ True, False, False,  True,  True],
       [False,  True,  True, False,  True]])

In [99]:
arr[arr>50]

array([72, 84, 66, 79, 54, 70, 83, 90, 92, 77, 61, 68, 94, 73, 80])

In [103]:
arr[2:4,[1,2]]

array([[92, 25],
       [38, 36]])

In [104]:
arr[0][0]=5000

In [105]:
arr

array([[5000,   39,   21,   12,   84],
       [  66,   79,   54,   70,   83],
       [  90,   92,   25,   46,   33],
       [  77,   38,   36,   61,   68],
       [  12,   94,   73,   30,   80]])

In [106]:
arr

array([[5000,   39,   21,   12,   84],
       [  66,   79,   54,   70,   83],
       [  90,   92,   25,   46,   33],
       [  77,   38,   36,   61,   68],
       [  12,   94,   73,   30,   80]])

In [107]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [108]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [109]:
arr2

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [110]:
arr1+arr2

array([[2, 3, 3],
       [3, 4, 2],
       [3, 4, 2]])

In [111]:
arr1*arr2

array([[1, 2, 2],
       [2, 4, 1],
       [2, 4, 1]])

In [112]:
arr1/arr2

array([[1. , 2. , 0.5],
       [0.5, 1. , 1. ],
       [2. , 1. , 1. ]])

In [113]:
arr1-arr2

array([[ 0,  1, -1],
       [-1,  0,  0],
       [ 1,  0,  0]])

In [115]:
arr1@arr2#matrix multiplication 

array([[6, 7, 5],
       [6, 7, 5],
       [7, 8, 7]])

In [116]:
arr1/0

C:\Users\tushar.ahire01\AppData\Local\Temp\ipykernel_26800\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [117]:
arr1+100

array([[101, 102, 101],
       [101, 102, 101],
       [102, 102, 101]])

In [119]:
arr1**3

array([[1, 8, 1],
       [1, 8, 1],
       [8, 8, 1]], dtype=int32)

In [120]:
#Broadcasting 

In [122]:
arr=np.zeros((4,4))

In [123]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
row= np.array([1,2,3,4])

In [125]:
row

array([1, 2, 3, 4])

In [126]:
arr +row#row vice 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [127]:
row.T

array([1, 2, 3, 4])

In [128]:
col=np.array([[1,2,3,4]])

In [129]:
col

array([[1, 2, 3, 4]])

In [131]:
col.T + arr #column vice

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [132]:
arr1 = np.random.randint(1,4 ,(3,4))

In [133]:
arr1

array([[3, 3, 1, 2],
       [1, 1, 2, 1],
       [2, 1, 2, 3]])

In [134]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.        , 1.41421356],
       [1.        , 1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356, 1.73205081]])

In [135]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  2.71828183,  7.3890561 ],
       [ 2.71828183,  2.71828183,  7.3890561 ,  2.71828183],
       [ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692]])

In [136]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.        , 0.30103   ],
       [0.        , 0.        , 0.30103   , 0.        ],
       [0.30103   , 0.        , 0.30103   , 0.47712125]])

In [137]:
np.average(arr1)

1.8333333333333333

In [138]:
np.max(arr1)

3